### ISSUE TITLE
Fix broken e2e tests, establish as part of the developer workflow

### ISSUE THREAD

**Issue by brendanarnold** [DFE-Digital/polis-whitelabel#33]
Fix the broken e2e tests and include as part of the `CONTRIBUTION` guidelines for PRs.

At the moment ...

* ` i18n.cy.js` fails - seems ligitimately that the internationalisation is broken
* Embed tests are skipped - there is a some funky setup needed for these
* Running direct on dev machine (so can get headed results) whilst pol.is is on VM causes failures
  * possibly a CORS thing since is referring to both `localhost` and an internal IP e.g. `192.168.64.5`

**Comment by patcon** [comment]
> there is a some funky setup needed for these

It's a bit odd, but simply adding a single static html file, so that embeds can be tried locally (prob better to make it cross-domain, and not host it on same server, but was a decent start to cover this important surface area that can easily silently break. I would not work too much longer without fixing it, or else it might be a hassle to git bisect and figure out where things went wrong :) )

**Comment by brendanarnold** [comment]
@patcon Yeah I created a seperate server for the testing - this should be stood-up before tests start. Although it worked when I loaded in the browser, I couldn't get this running in Cypress when running from a different place to the server (i.e. `server` on the Devcontainer and the `embed-server` locally), it just couldn't connect to the local embed server - I think becuase Cypress didn't like `localhost` being mapped to two different source locations and/or some funky Docker networking and/or some funky work computer firewall thing. They work when served both in the Devcontainer though. I realise this isn't ideal since it isn't really true to a proper embedded setup but I couldn't figure out the root cause in a reasonable time.
