### ISSUE TITLE
Remove legacy code and establish developer workflow

### ISSUE THREAD

**Issue by brendanarnold** [DFE-Digital/polis-whitelabel#7]
Inline with the 'white label' aims for this fork of pol.is - we are looking to merge in many of the changes from https://github.com/sirodoht/suburb which include ...

* Docker config removed
* Nix config added
* Heroku config removed
* Bundlewatch removed
* nginx config removed
* Caddy config added
* All components now use a single Node.js version
* e2e tests upgraded to latest Node.js LTS version
* e2e cypress updated to v10
* Stripe integration removed
* Database setup has moved into its own directory
* Separate server.ts into handlers.ts and helpers.ts
* Intercom removed

Plan is to review the changes [using the compare feature ](https://github.com/sirodoht/suburb/compare/8caec70ce2c207fa2f8d0462b2461b2089989c1d..37cc02d037aaedb5ee38c9a31064fc78e348d7b6) and cherry pick those that are approapriate for the white label project.

**Comment by patcon** [comment]
One more thing to add, is a way to set the name of the project in all the front-facing interfaces to be something other than Polis. That will allow people to easily host without using the Polis brand.

Also: Easily swapping out the `/home` page might also be a nice-to-have. For example, this could also provide a more general default landing page. The page could be less opinionated about upstream repo, and perhaps point to collectively-maintained documentation rather than docs stewarded exclusively by Computational Democracy Project.

(Once the g0v.london hacknight gets running without as much need for my offering as much social infrastructure support, I'd be happy to support on these tickets! 🎉 )

**Comment by patcon** [comment]
Related: https://github.com/compdemocracy/polis/issues/263

Specifically:
- removing intercom:
  - https://github.com/compdemocracy/polis/pull/1233
  - alt: https://github.com/compdemocracy/polis/pull/1547
- removing stripe/coupon/plans refernces: https://github.com/compdemocracy/polis/pull/1235
- removing canvas learning management system (LMS): https://github.com/compdemocracy/polis/pull/1236
